// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
export interface VersionCommit { hash: string; date: string; subject: string; }
export const VERSION: string = "v0.1.216";
export const UPDATED: string = "2026-06-15";
export const COMMITS: VersionCommit[] = [
  {
    "hash": "a7d8b37",
    "date": "2026-06-15",
    "subject": "Security: next 16.2.9 + react 19.2.7, session guards on write routes, shared Notion retry, parallel dashboard carry-over"
  },
  {
    "hash": "3664d31",
    "date": "2026-06-15",
    "subject": "Daily To Do: keep shopping list tile above checked tasks while items remain"
  },
  {
    "hash": "a26575b",
    "date": "2026-06-13",
    "subject": "Costings: hide made-in-house components from tiles (Fennel Slaw etc.)"
  },
  {
    "hash": "ddfe0bc",
    "date": "2026-06-13",
    "subject": "Margin review matcher v2.2"
  },
  {
    "hash": "501ec1d",
    "date": "2026-06-12",
    "subject": "Margin review: modifier aliases, LARGE promotion, mocha/matcha/chai mapping, diagnostics"
  },
  {
    "hash": "b1775a1",
    "date": "2026-06-12",
    "subject": "Resync Apps Script from production: Cost sync (food+coffee) + June changes"
  },
  {
    "hash": "5a846c7",
    "date": "2026-06-12",
    "subject": "Margin review: qty/wk on all matched tiles, not just flagged"
  },
  {
    "hash": "8516f7c",
    "date": "2026-06-11",
    "subject": "Margin review: matcher v2.1 + daily trigger; fold review into product tiles"
  },
  {
    "hash": "e54e547",
    "date": "2026-06-11",
    "subject": "Margin review + pack-size detection"
  },
  {
    "hash": "235c0e0",
    "date": "2026-06-10",
    "subject": "Shopping list: checked items sink to bottom, cleared end of day"
  },
  {
    "hash": "a7d61fe",
    "date": "2026-06-10",
    "subject": "Disable mobile zoom"
  },
  {
    "hash": "ca6c75d",
    "date": "2026-06-09",
    "subject": "Uppercase unit + affected text in ingredient cards"
  },
  {
    "hash": "08690e0",
    "date": "2026-06-09",
    "subject": "fix: onAdd type void not Promise<void>"
  },
  {
    "hash": "031b2f5",
    "date": "2026-06-08",
    "subject": "perf: fire-and-forget add-task — modal closes instantly, API runs in background"
  },
  {
    "hash": "8793c0e",
    "date": "2026-06-08",
    "subject": "fix: capitalise BACK button"
  },
  {
    "hash": "d83b061",
    "date": "2026-06-08",
    "subject": "fix: persist recurring task suppression via checked-state, survive hard refresh"
  },
  {
    "hash": "07e25cb",
    "date": "2026-06-08",
    "subject": "fix: bust CDN cache after mutations, parallelize state+week fetch, fix fromDate in drag drop"
  },
  {
    "hash": "56c260e",
    "date": "2026-06-08",
    "subject": "perf: parallelize classify+children fetch in add-task, optimistic roster count"
  },
  {
    "hash": "326132f",
    "date": "2026-06-08",
    "subject": "fix: suppress recurring tasks moved to another day (double-show bug)"
  },
  {
    "hash": "d7d140c",
    "date": "2026-06-06",
    "subject": "Shopping link row: uppercase text, scroll to widget on open"
  }
];
