// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
export interface VersionCommit { hash: string; date: string; subject: string; }
export const VERSION: string = "v0.1.182";
export const UPDATED: string = "2026-06-05";
export const COMMITS: VersionCommit[] = [
  {
    "hash": "manual",
    "date": "2026-06-05",
    "subject": "Shopping List: standalone widget + launcher tile + Daily To Do link row"
  },
  {
    "hash": "a07a4e1",
    "date": "2026-06-03",
    "subject": "Auto-refresh: reload on day rollover, soft-refresh on refocus"
  },
  {
    "hash": "be828f0",
    "date": "2026-06-02",
    "subject": "Full widget names on launcher tiles"
  },
  {
    "hash": "7f5a3f9",
    "date": "2026-06-02",
    "subject": "Square launcher grid for collapsed widgets"
  },
  {
    "hash": "108ebe7",
    "date": "2026-06-02",
    "subject": "Collapse remaining widgets to expandable tiles"
  },
  {
    "hash": "2d3034d",
    "date": "2026-06-01",
    "subject": "Unbold all dashboard widget text"
  },
  {
    "hash": "0c1a356",
    "date": "2026-06-01",
    "subject": "Projects card polish: caps on form controls, uniform tile sizing, right-side dropdown arrow, swipe-to-delete projects"
  },
  {
    "hash": "fe00c2f",
    "date": "2026-06-01",
    "subject": "Projects card: uppercase, tile-styled capture box, collapsible project tiles, Claude logo"
  },
  {
    "hash": "b10df18",
    "date": "2026-06-01",
    "subject": "Replace in-widget chat with Claude deep-link handoff (Cowork on desktop, clipboard on mobile)"
  },
  {
    "hash": "26cbb46",
    "date": "2026-06-01",
    "subject": "Add archive-to-trash for projects (/api/archive-project + card button)"
  },
  {
    "hash": "679b628",
    "date": "2026-06-01",
    "subject": "Merge Brain Dump into Projects card with AI-assisted capture"
  },
  {
    "hash": "7a5d94c",
    "date": "2026-06-01",
    "subject": "Add TakeawayCupCounter — auto Planetware cup reorder at 10k"
  },
  {
    "hash": "9474ee7",
    "date": "2026-06-01",
    "subject": "Shared task-parsing lib, edge cache on dashboard + week-tasks, page_size cleanup"
  },
  {
    "hash": "828b5dd",
    "date": "2026-06-01",
    "subject": "Opus 4.8 + maxDuration, Notion retry, Deputy parse guard, weather map sync"
  },
  {
    "hash": "4a44b8d",
    "date": "2026-06-01",
    "subject": "Opus 4.8, Notion retry, Deputy parse guard, weather map sync"
  },
  {
    "hash": "61ca77c",
    "date": "2026-05-31",
    "subject": "Fix dill mapping: dill is in Chicken Schnitta slaw, not tuna"
  },
  {
    "hash": "b87f94e",
    "date": "2026-05-30",
    "subject": "Fix PFD archiver sender address (ar@ → PFDPortal@)"
  },
  {
    "hash": "64375b0",
    "date": "2026-05-26",
    "subject": "Add quantity support to shopping list (set on add, tap to adjust)"
  },
  {
    "hash": "029c7c3",
    "date": "2026-05-26",
    "subject": "Enable delete for recurring tasks in Week Ahead"
  },
  {
    "hash": "6799ab3",
    "date": "2026-05-26",
    "subject": "Remove recurrence hint text from Week Ahead add panel"
  },
  {
    "hash": "9b38402",
    "date": "2026-05-26",
    "subject": "Add recurring task options to Week Ahead (daily/weekly/fortnightly/monthly)"
  }
];
