// Generates app/lib/version.ts from git at build time (runs as `prebuild`).
// Version = commit count → v0.1.<count>; "What's New" = recent commit subjects.
// Fully defensive: if git is unavailable (or a shallow CI clone), it falls back
// to Vercel's commit env vars so the build never breaks.
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'app', 'lib', 'version.ts');

const sh = (cmd) => execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();

let count = 0;
let commits = [];

try {
  // A shallow CI clone hides history — deepen it so count + log are accurate.
  try { if (sh('git rev-parse --is-shallow-repository') === 'true') sh('git fetch --unshallow --quiet'); } catch { /* best effort */ }

  count = parseInt(sh('git rev-list --count HEAD'), 10) || 0;

  // \x1f (unit separator) keeps subjects with commas/pipes intact.
  const raw = sh("git log -20 --no-merges --pretty=format:%h%x1f%ad%x1f%s --date=short");
  commits = raw.split('\n').filter(Boolean).map((line) => {
    const [hash, date, subject] = line.split('\x1f');
    return { hash, date, subject };
  });
} catch {
  // No git (or it failed): fall back to Vercel's single-commit env vars.
  const sha = (process.env.VERCEL_GIT_COMMIT_SHA || '').slice(0, 7);
  const msg = process.env.VERCEL_GIT_COMMIT_MESSAGE || '';
  if (sha) commits = [{ hash: sha, date: new Date().toISOString().slice(0, 10), subject: msg.split('\n')[0] || 'Latest deploy' }];
}

const version = count > 0 ? `v0.1.${count}` : 'v0.1.0';
// "Updated" date comes from the latest commit (stable per HEAD) rather than a
// build timestamp — so regenerating at the same commit produces an identical
// file and never creates git noise.
const updated = commits[0]?.date || new Date().toISOString().slice(0, 10);

const body = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
export interface VersionCommit { hash: string; date: string; subject: string; }
export const VERSION: string = ${JSON.stringify(version)};
export const UPDATED: string = ${JSON.stringify(updated)};
export const COMMITS: VersionCommit[] = ${JSON.stringify(commits, null, 2)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`[gen-version] ${version} · ${commits.length} commits → app/lib/version.ts`);
